definitions:
  model.Image:
    properties:
      block_id:
        type: string
      create_at:
        type: string
      data:
        type: string
      error:
        type: string
      id:
        type: string
      path:
        type: string
      status:
        type: string
      user_id:
        type: string
    type: object
  model.ImageUpdate:
    properties:
      data:
        type: string
    type: object
info:
  contact: {}
  license: {}
  title: OCR BACKEND API
  version: "1.0"
paths:
  /api/v1/auth/image/{image_id}:
    get:
      description: get list image
      parameters:
      - description: image id
        in: path
        name: image_id
        type: string
      - description: '''Bearer '' + token'
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Image'
            type: array
      summary: image
      tags:
      - Images
    post:
      description: update image
      parameters:
      - description: image id
        in: path
        name: image_id
        type: string
      - description: '''Bearer '' + token'
        in: header
        name: Authorization
        required: true
        type: string
      - description: image content
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.ImageUpdate'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: image
      tags:
      - Images
  /api/v1/auth/images:
    get:
      description: get list image
      parameters:
      - description: image id
        in: query
        name: id
        type: string
      - description: user id
        in: query
        name: user_id
        type: string
      - description: '''Bearer '' + token'
        in: header
        name: Authorization
        required: true
        type: string
      - description: status
        in: query
        name: status
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Image'
            type: array
      summary: image
      tags:
      - Images
  /api/v1/auth/object:
    post:
      description: upload object
      parameters:
      - description: add block id
        in: header
        name: block_id
        type: string
      - description: '''Bearer '' + token'
        in: header
        name: Authorization
        required: true
        type: string
      - description: add file multipart/form-data
        in: formData
        name: file
        required: true
        type: file
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Image'
        "400":
          description: some info
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
        "500":
          description: '...'
          schema:
            type: string
      summary: upload, download object
      tags:
      - Object
  /api/v1/auth/object/{id}:
    get:
      description: download object
      parameters:
      - description: object id
        in: path
        name: id
        required: true
        type: string
      - description: '''Bearer '' + token'
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "400":
          description: some info
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
        "500":
          description: '...'
          schema:
            type: string
      summary: upload, download object
      tags:
      - Object
swagger: "2.0"
